# Cloud Build configuration for Podcast Pro
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '--all-tags',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=${_RUN_SERVICE_ACCOUNT_NAME}@$PROJECT_ID.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=$PROJECT_ID:${_REGION}:${_SQL_INSTANCE_NAME}'
      - '--set-env-vars=INSTANCE_CONNECTION_NAME=$PROJECT_ID:${_REGION}:${_SQL_INSTANCE_NAME},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},GCS_BUCKET_NAME=${_GCS_BUCKET}'
      - '--set-secrets=DB_PASS=DB_PASS:latest,FLASK_SECRET_KEY=FLASK_SECRET_KEY:latest'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--concurrency=80'
      - '--min-instances=0'
      - '--max-instances=10'

# Substitution variables
substitutions:
  _REGION: 'us-west1'
  _AR_REPO: 'podcast-pro-images'
  _SERVICE_NAME: 'podcast-pro-backend'
  _SQL_INSTANCE_NAME: 'podcast-pro-db'
  _DB_USER: 'postgres'
  _DB_NAME: 'postgres'
  _GCS_BUCKET: 'podcast-pro-464303-media'
  _RUN_SERVICE_ACCOUNT_NAME: 'podcast-run-sa'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

timeout: '1200s'
